MyFunction:
  Type: AWS::Serverless::Function
  Properties:
    Runtime: python3.11
    Handler: app.lambda_handler
    CodeUri: src/
    Policies:
      - S3ReadPolicy: #----> S3
          BucketName: my-bucket-name
-------------------------------------------------
MyFunction:
  Type: AWS::Serverless::Function
  Properties:
    Runtime: python3.11
    Handler: app.lambda_handler
    CodeUri: src/
    Policies:
      - DynamoDBCrudPolicy: #----> DynamoDB
          TableName: MyTable
-------------------------------------------------
MyFunction:
  Type: AWS::Serverless::Function
  Properties:
    Runtime: python3.11
    Handler: app.lambda_handler
    CodeUri: src/
    Policies:
      - SQSPollerPolicy: #----> SQS
          QueueName: MyQueue
-------------------------------------------------
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM demo - S3 Read, DynamoDB CRUD, SQS Poller (Policy Templates)

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: python3.11

Resources:

  # ----------- Shared Resources -----------
  DemoBucket:
    Type: AWS::S3::Bucket

  DemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  DemoQueue:
    Type: AWS::SQS::Queue

  # ----------- 1) Lambda: Read from S3 -----------
  LambdaS3Reader:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/s3reader/
      Handler: app.lambda_handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DemoBucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref DemoBucket

  # ----------- 2) Lambda: CRUD on DynamoDB -----------
  LambdaDynamoCrud:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/dynamocrud/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DemoTable
      Environment:
        Variables:
          TABLE_NAME: !Ref DemoTable

  # ----------- 3) Lambda: Poll SQS -----------
  LambdaSqsPoller:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/sqspoller/
      Handler: app.lambda_handler
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt DemoQueue.QueueName
      Environment:
        Variables:
          QUEUE_URL: !Ref DemoQueue

      # (اختیاری ولی رایج) اگر می‌خواهی Lambda با Event Source Mapping اتوماتیک پیام‌ها را بگیرد:
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt DemoQueue.Arn
            BatchSize: 10

Outputs:
  BucketName:
    Description: Demo S3 bucket name
    Value: !Ref DemoBucket

  TableName:
    Description: Demo DynamoDB table name
    Value: !Ref DemoTable

  QueueUrl:
    Description: Demo SQS queue URL
    Value: !Ref DemoQueue

  S3ReaderFunctionName:
    Description: Lambda function that can read from S3
    Value: !Ref LambdaS3Reader

  DynamoCrudFunctionName:
    Description: Lambda function that can CRUD DynamoDB
    Value: !Ref LambdaDynamoCrud

  SqsPollerFunctionName:
    Description: Lambda function that polls SQS
    Value: !Ref LambdaSqsPoller



