# buildspec.yml
version: 0.2

phases:
  install:
    commands:
      - curl -Lo packer.zip https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip
      - unzip packer.zip
      - mv packer /usr/local/bin/

  build:
    commands:
      - packer init .
      - packer build ami.pkr.hcl
